### ISSUE TITLE
Container fails to start due to missing config file

### ISSUE THREAD

**Issue by Qwertie-** [linuxserver/docker-dokuwiki#31]
[linuxserverurl]: https://linuxserver.io

## Expected Behavior
Expect the container to start with default setup

## Current Behavior
```
Container fails to start with error repeatedly logged
dokuwiki     | [01-Mar-2021 02:03:46] ERROR: failed to post process the configuration
dokuwiki     | [01-Mar-2021 02:03:46] ERROR: FPM initialization failed
dokuwiki     | nginx: [emerg] open() "/config/nginx/nginx.conf" failed (2: No such file or directory)
dokuwiki     | [01-Mar-2021 02:03:47] ERROR: failed to open error_log (/config/log/php/error.log): No such file or directory (2)

```

## Steps to Reproduce
Start container with this docker compose

```
  dokuwiki:
    image: ghcr.io/linuxserver/dokuwiki
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/core/config/dokuwiki:/config
    restart: unless-stopped
```

`/home/core/config/dokuwiki` is just an empty dir. I'm guessing I need to add some nginx config but I'm not sure what.

## Environment
**OS:** Fedora CoreOS 
**CPU architecture:** x86_64
**How docker service was installed:**
It comes preinstalled with Fedora CoreOS
$ docker --version
Docker version 19.03.13, build 4484c46
